# Generated by Django 2.2.4 on 2019-08-29 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cell_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='habitable',
            field=models.BooleanField(default=True),
        ),
    ]
